version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: olx_db
      POSTGRES_USER: olx_user
      POSTGRES_PASSWORD: olx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U olx_user -d olx_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      OLX_DATABASE_URL: postgresql://olx_user:olx_password@db:5432/olx_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app.log:/app/app.log
    restart: unless-stopped

volumes:
  postgres_data:
