"""Add source field to ItemRecord

Revision ID: 6f5f9fdb731d
Revises: 8d2ea177ed66
Create Date: 2025-08-07 11:16:31.455767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5f9fdb731d"
down_revision: Union[str, Sequence[str], None] = "8d2ea177ed66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item_records", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item_records", "source")
    # ### end Alembic commands ###
