"""Initial migration

Revision ID: 8d2ea177ed66
Revises: 
Create Date: 2025-08-06 19:18:07.244918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d2ea177ed66"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_url", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_at_pretty", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_records_id"), "item_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_item_records_item_url"), "item_records", ["item_url"], unique=True
    )
    op.create_index(
        op.f("ix_item_records_source_url"), "item_records", ["source_url"], unique=False
    )
    op.create_table(
        "monitoring_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("last_got_item", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "name", name="uix_chat_id_name"),
    )
    op.create_index(
        op.f("ix_monitoring_tasks_chat_id"),
        "monitoring_tasks",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitoring_tasks_id"), "monitoring_tasks", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitoring_tasks_id"), table_name="monitoring_tasks")
    op.drop_index(op.f("ix_monitoring_tasks_chat_id"), table_name="monitoring_tasks")
    op.drop_table("monitoring_tasks")
    op.drop_index(op.f("ix_item_records_source_url"), table_name="item_records")
    op.drop_index(op.f("ix_item_records_item_url"), table_name="item_records")
    op.drop_index(op.f("ix_item_records_id"), table_name="item_records")
    op.drop_table("item_records")
    # ### end Alembic commands ###
