"""add cities districts and location filtering

Revision ID: b9739b6f6698
Revises: 6f5f9fdb731d
Create Date: 2026-01-26 18:12:20.295434

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9739b6f6698"
down_revision: Union[str, Sequence[str], None] = "6f5f9fdb731d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_raw", sa.String(length=255), nullable=False),
        sa.Column("name_normalized", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_normalized"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name_raw", sa.String(length=255), nullable=False),
        sa.Column("name_normalized", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id", "name_normalized", name="uix_city_district"),
    )
    op.create_index(op.f("ix_districts_id"), "districts", ["id"], unique=False)
    op.create_table(
        "monitoring_task_districts",
        sa.Column("monitoring_task_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["monitoring_task_id"], ["monitoring_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("monitoring_task_id", "district_id"),
    )
    op.add_column("item_records", sa.Column("city_id", sa.Integer(), nullable=True))
    op.add_column("item_records", sa.Column("district_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_item_records_city_id"), "item_records", ["city_id"], unique=False
    )
    op.create_index(
        op.f("ix_item_records_district_id"),
        "item_records",
        ["district_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "item_records", "cities", ["city_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "item_records", "districts", ["district_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("monitoring_tasks", sa.Column("city_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_monitoring_tasks_city_id"),
        "monitoring_tasks",
        ["city_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "monitoring_tasks", "cities", ["city_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "monitoring_tasks", type_="foreignkey")
    op.drop_index(op.f("ix_monitoring_tasks_city_id"), table_name="monitoring_tasks")
    op.drop_column("monitoring_tasks", "city_id")
    op.drop_constraint(None, "item_records", type_="foreignkey")
    op.drop_constraint(None, "item_records", type_="foreignkey")
    op.drop_index(op.f("ix_item_records_district_id"), table_name="item_records")
    op.drop_index(op.f("ix_item_records_city_id"), table_name="item_records")
    op.drop_column("item_records", "district_id")
    op.drop_column("item_records", "city_id")
    op.drop_table("monitoring_task_districts")
    op.drop_index(op.f("ix_districts_id"), table_name="districts")
    op.drop_table("districts")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
