"""add graphql capture fields to monitoring_tasks

Revision ID: e34b7384ae64
Revises: b9739b6f6698
Create Date: 2026-02-10 16:17:23.613870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e34b7384ae64"
down_revision: Union[str, Sequence[str], None] = "b9739b6f6698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitoring_tasks",
        sa.Column("graphql_endpoint", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "monitoring_tasks", sa.Column("graphql_payload", sa.JSON(), nullable=True)
    )
    op.add_column(
        "monitoring_tasks", sa.Column("graphql_headers", sa.JSON(), nullable=True)
    )
    op.add_column(
        "monitoring_tasks",
        sa.Column("graphql_captured_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitoring_tasks", "graphql_captured_at")
    op.drop_column("monitoring_tasks", "graphql_headers")
    op.drop_column("monitoring_tasks", "graphql_payload")
    op.drop_column("monitoring_tasks", "graphql_endpoint")
    # ### end Alembic commands ###
