name: Run tests

on:
  pull_request:
    branches:
      - main
      - stage
  push:
    branches:
      - main
      - stage

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: "3.12"}

      - name: Install deps + coverage plugin
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests & create coverage.xml
        run: |
          pytest -v \
            --cov=. \
            --cov-config=.coveragerc \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=60 \
            --junitxml=junit.xml -o junit_family=legacy
        env:
          DATABASE_URL: "postgresql://user:password@host:9999/database"

